### ISSUE TITLE
Multiple tables export issue

### ISSUE THREAD

**Issue by dxerw** [hhurz/tableExport.jquery.plugin#161]
Hello there,

I've noticed even the demo got an error. While checking out to export 2 tables it seems like the content of the 1st table is also at the start of the 2nd table together with it's own content. Can you please check it out?

Thank you!

**Comment by hhurz** [comment]
@dxerw Thanks for reporting this issue. I fixed that issue and released an updated version.

**Comment by dxerw** [comment]
Thank you for the fast reply! I've tried the new version but I still get the same results :/

**Comment by hhurz** [comment]
Because its working for me, I need some more details what exactly you are doing. Just to clarify: are we talking about pdf export? Export of multiple tables ist not realy working for other formats. Thus the last fix and release only concerned with pdf export.

**Comment by dxerw** [comment]
Ohh my bad I thought I mentioned it. I was talking about the excel export. Let me show you with a pic
![tableexporterror](https://cloud.githubusercontent.com/assets/17804262/25565040/c8727746-2dc8-11e7-8188-d6ce28a7b31f.png)

**Comment by hhurz** [comment]
As stated before, you can't export multiple different tables within a single excel file. The major reason for this is, that the excel 2000 format, which is used by this plugin, doesn't allow multiple tables in a single file.

**Comment by killergege** [comment]
Maybe you should remove the multiple table example then ?
The file "test/multipleExcel.html" produces the picture above, so it's obviously not working as one would expect. 
Or maybe it is a test that is supposed to fail ?

Reading the issues history, I see that the feature was implemented (or at least planned) before. Was it abandonned ?

**Comment by hhurz** [comment]
Nope, I recently changed the example to work with the new Excel 2003 XML Spreadsheet format.
